<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="REZCHIKOV" failures="13" tests="29" name="Command line test" time="0.225" errors="0" timestamp="2024-02-24T01:05:10 MSK">
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitPowTest" time="0.005"/>
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitPowTest" time="0.004"/>
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitPowTest" time="0.012">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [46.7653718] but found [27.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [46.7653718] but found [27.0]
at org.rntgroup.test.PowerFunctionTest.unitPowTest(PowerFunctionTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitPowTest -->
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitPowTest" time="0.001"/>
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitSqrtNegativeNumbersTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Expected exception not throw">
      <![CDATA[java.lang.AssertionError: Expected exception not throw
at org.rntgroup.test.PowerFunctionTest.unitSqrtNegativeNumbersTest(PowerFunctionTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- unitSqrtNegativeNumbersTest -->
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitSqrtTest" time="0.001"/>
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitSqrtTest" time="0.001"/>
  <testcase classname="org.rntgroup.test.PowerFunctionTest" name="unitSqrtTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.SingDefinitionTest" name="unitIsNegativeTest" time="0.001"/>
  <testcase classname="org.rntgroup.test.SingDefinitionTest" name="unitIsNegativeTest" time="0.002"/>
  <testcase classname="org.rntgroup.test.SingDefinitionTest" name="unitIsNegativeTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.SingDefinitionTest" name="unitIsPositiveTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.SingDefinitionTest" name="unitIsPositiveTest" time="0.001"/>
  <testcase classname="org.rntgroup.test.SingDefinitionTest" name="unitIsPositiveTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.5] but found [0.8660254037844386]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.5] but found [0.8660254037844386]
at org.rntgroup.test.TrigonometricFunctionTest.unitCosTest(TrigonometricFunctionTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [-1.0] but found [-1.2246467991473532E-16]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [-1.0] but found [-1.2246467991473532E-16]
at org.rntgroup.test.TrigonometricFunctionTest.unitCosTest(TrigonometricFunctionTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [1.0] but found [0.0]
at org.rntgroup.test.TrigonometricFunctionTest.unitCosTest(TrigonometricFunctionTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [0.9171523356672744]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [0.9171523356672744]
at org.rntgroup.test.TrigonometricFunctionTest.unitCtgTest(TrigonometricFunctionTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.404] but found [0.9606886408725873]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.404] but found [0.9606886408725873]
at org.rntgroup.test.TrigonometricFunctionTest.unitCtgTest(TrigonometricFunctionTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitCtgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [-1.0] but found [-0.6557942026326724]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [-1.0] but found [-0.6557942026326724]
at org.rntgroup.test.TrigonometricFunctionTest.unitCtgTest(TrigonometricFunctionTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitSinTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.5] but found [0.49999999999999994]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.5] but found [0.49999999999999994]
at org.rntgroup.test.TrigonometricFunctionTest.unitSinTest(TrigonometricFunctionTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitSinTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitTgTest" time="0.0"/>
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitTgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [1.0]
at org.rntgroup.test.TrigonometricFunctionTest.unitTgTest(TrigonometricFunctionTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitTgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.364] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.364] but found [1.0]
at org.rntgroup.test.TrigonometricFunctionTest.unitTgTest(TrigonometricFunctionTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitTgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [1.0]
at org.rntgroup.test.TrigonometricFunctionTest.unitTgTest(TrigonometricFunctionTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.test.TrigonometricFunctionTest" name="unitTgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [-1.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [-1.0] but found [1.0]
at org.rntgroup.test.TrigonometricFunctionTest.unitTgTest(TrigonometricFunctionTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
</testsuite> <!-- Command line test -->
